<?php
/**
 * LOKA - Export Report to PDF
 */

requireRole(ROLE_APPROVER);

require_once BASE_PATH . '/vendor/tecnickcom/tcpdf/tcpdf.php';

$startDate = get('start_date', date('Y-m-01'));
$endDate = get('end_date', date('Y-m-t'));
$maxRows = 1000;

$requests = db()->fetchAll(
    "SELECT r.id, r.created_at, r.start_datetime, r.end_datetime, r.purpose, r.destination,
            r.passenger_count, r.status, u.name as requester, d.name as department,
            v.plate_number as vehicle, dr_u.name as driver,
            r.actual_dispatch_datetime, r.actual_arrival_datetime
     FROM requests r
     JOIN users u ON r.user_id = u.id
     LEFT JOIN departments d ON r.department_id = d.id
     LEFT JOIN vehicles v ON r.vehicle_id = v.id AND v.deleted_at IS NULL
     LEFT JOIN drivers dr ON r.driver_id = dr.id AND dr.deleted_at IS NULL
     LEFT JOIN users dr_u ON dr.user_id = dr_u.id
     WHERE r.created_at BETWEEN ? AND ? AND r.deleted_at IS NULL
     ORDER BY r.created_at DESC
     LIMIT ?",
    [$startDate, $endDate . ' 23:59:59', $maxRows]
);

auditLog('data_export', 'requests', null, null, ['format' => 'pdf', 'rows' => count($requests)]);

$filename = 'fleet_report_' . $startDate . '_to_' . $endDate;
$title = 'Fleet Report - ' . $startDate . ' to ' . $endDate;

$pdf = new TCPDF('L', PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
$pdf->SetCreator('LOKA Fleet Management');
$pdf->SetAuthor(currentUser()->name);
$pdf->SetTitle($title);
$pdf->SetHeaderData('', 0, 'DICT - Fleet Management Report', 'Generated: ' . date('Y-m-d H:i:s') . ' | Period: ' . $startDate . ' to ' . $endDate);
$pdf->setHeaderFont([PDF_FONT_NAME_MAIN, '', 10]);
$pdf->setFooterFont([PDF_FONT_NAME_DATA, '', 8]);
$pdf->SetMargins(10, 15, 10);
$pdf->SetAutoPageBreak(TRUE, 15);
$pdf->AddPage();
$pdf->SetFont('helvetica', '', 8);

$columns = ['ID', 'Created', 'Scheduled Start', 'Scheduled End', 'Purpose', 'Destination', 'Passengers', 'Status', 'Requester', 'Department', 'Vehicle', 'Driver'];
$colWidths = [12, 25, 25, 25, 40, 40, 15, 18, 28, 28, 20, 25];

$pdf->SetFont('helvetica', 'B', 8);
$pdf->SetFillColor(13, 110, 253);
$pdf->SetTextColor(255, 255, 255);
foreach ($columns as $i => $col) {
    $pdf->Cell($colWidths[$i], 7, $col, 1, 0, 'C', true);
}
$pdf->Ln();

$pdf->SetFillColor(248, 248, 248);
$pdf->SetTextColor(0, 0, 0);
$pdf->SetFont('helvetica', '', 7);

$fill = false;
foreach ($requests as $row) {
    $statusColors = [
        'approved' => [40, 167, 69],
        'rejected' => [220, 53, 69],
        'completed' => [23, 162, 184],
        'pending' => [255, 193, 7],
        'pending_motorpool' => [255, 193, 7],
        'revision' => [253, 126, 20],
    ];
    
    $rowData = [
        $row->id,
        date('M j, Y', strtotime($row->created_at)),
        date('M j, Y H:i', strtotime($row->start_datetime)),
        date('M j, Y H:i', strtotime($row->end_datetime)),
        strlen($row->purpose) > 30 ? substr($row->purpose, 0, 30) . '...' : $row->purpose,
        strlen($row->destination) > 30 ? substr($row->destination, 0, 30) . '...' : $row->destination,
        $row->passenger_count,
        ucfirst($row->status),
        $row->requester,
        $row->department ?: '-',
        $row->vehicle ?: '-',
        $row->driver ?: '-'
    ];
    
    foreach ($rowData as $i => $val) {
        $pdf->Cell($colWidths[$i], 6, $val, 1, 0, 'L', $fill);
    }
    $pdf->Ln();
    $fill = !$fill;
}

$pdf->Ln(5);
$pdf->SetFont('helvetica', 'I', 8);
$pdf->Cell(0, 5, 'Total Records: ' . count($requests) . ' | Generated by LOKA Fleet Management System', 0, 1, 'C');

$pdf->Output($filename . '.pdf', 'D');
exit;
