<?php
/**
 * LOKA - Export Vehicle History to PDF
 */

requireRole(ROLE_APPROVER);

require_once BASE_PATH . '/vendor/tecnickcom/tcpdf/tcpdf.php';

$vehicleId = get('vehicle_id');
$startDate = get('start_date', date('Y-m-01'));
$endDate = get('end_date', date('Y-m-t'));

if (!$vehicleId) {
    redirectWith('/?page=reports&action=vehicle-history', 'danger', 'Please select a vehicle.');
}

$vehicleInfo = db()->fetch(
    "SELECT v.*, vt.name as type_name
     FROM vehicles v
     LEFT JOIN vehicle_types vt ON v.vehicle_type_id = vt.id
     WHERE v.id = ? AND v.deleted_at IS NULL",
    [$vehicleId]
);

if (!$vehicleInfo) {
    redirectWith('/?page=reports&action=vehicle-history', 'danger', 'Vehicle not found.');
}

$trips = db()->fetchAll(
    "SELECT r.id, r.start_datetime, r.end_datetime, r.purpose, r.destination,
            r.status, r.passenger_count, r.actual_dispatch_datetime, r.actual_arrival_datetime,
            u.name as requester_name, d.name as department_name,
            dr_user.name as driver_name,
            TIMESTAMPDIFF(MINUTE, r.start_datetime, r.end_datetime) as planned_duration,
            TIMESTAMPDIFF(MINUTE, r.actual_dispatch_datetime, r.actual_arrival_datetime) as actual_duration
     FROM requests r
     JOIN users u ON r.user_id = u.id
     LEFT JOIN departments d ON r.department_id = d.id
     LEFT JOIN drivers dr ON r.driver_id = dr.id
     LEFT JOIN users dr_user ON dr.user_id = dr_user.id
     WHERE r.vehicle_id = ? 
     AND r.start_datetime BETWEEN ? AND ?
     AND r.deleted_at IS NULL
     ORDER BY r.start_datetime DESC",
    [$vehicleId, $startDate, $endDate . ' 23:59:59']
);

$filename = 'vehicle_history_' . $vehicleInfo->plate_number . '_' . $startDate . '_to_' . $endDate;
$title = 'Vehicle History Report - ' . $vehicleInfo->plate_number;

$pdf = new TCPDF('L', PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
$pdf->SetCreator('LOKA Fleet Management');
$pdf->SetAuthor(currentUser()->name);
$pdf->SetTitle($title);
$pdf->SetHeaderData('', 0, 'DICT - Vehicle History Report', 
    $vehicleInfo->plate_number . ' - ' . $vehicleInfo->make . ' ' . $vehicleInfo->model . 
    ' | Period: ' . $startDate . ' to ' . $endDate);
$pdf->setHeaderFont([PDF_FONT_NAME_MAIN, '', 10]);
$pdf->setFooterFont([PDF_FONT_NAME_DATA, '', 8]);
$pdf->SetMargins(10, 15, 10);
$pdf->SetAutoPageBreak(TRUE, 15);
$pdf->AddPage();
$pdf->SetFont('helvetica', '', 8);

$pdf->SetFont('helvetica', 'B', 10);
$pdf->Cell(0, 8, 'Vehicle Information', 0, 1);
$pdf->SetFont('helvetica', '', 9);
$pdf->Cell(40, 6, 'Plate Number:', 0, 0);
$pdf->Cell(50, 6, $vehicleInfo->plate_number, 0, 0);
$pdf->Cell(40, 6, 'Make/Model:', 0, 0);
$pdf->Cell(0, 6, $vehicleInfo->make . ' ' . $vehicleInfo->model, 0, 1);
$pdf->Cell(40, 6, 'Type:', 0, 0);
$pdf->Cell(50, 6, $vehicleInfo->type_name ?: '-', 0, 0);
$pdf->Cell(40, 6, 'Status:', 0, 0);
$pdf->Cell(0, 6, ucfirst($vehicleInfo->status), 0, 1);
$pdf->Cell(40, 6, 'Mileage:', 0, 0);
$pdf->Cell(50, 6, number_format($vehicleInfo->mileage ?? 0) . ' km', 0, 0);
$pdf->Cell(40, 6, 'Year:', 0, 0);
$pdf->Cell(0, 6, $vehicleInfo->year ?: '-', 0, 1);
$pdf->Ln(5);

$columns = ['ID', 'Date/Time', 'Destination', 'Requester', 'Driver', 'Status', 'Duration'];
$colWidths = [15, 45, 60, 40, 35, 25, 25];

$pdf->SetFont('helvetica', 'B', 8);
$pdf->SetFillColor(13, 110, 253);
$pdf->SetTextColor(255, 255, 255);
foreach ($columns as $i => $col) {
    $pdf->Cell($colWidths[$i], 7, $col, 1, 0, 'C', true);
}
$pdf->Ln();

$pdf->SetFillColor(248, 248, 248);
$pdf->SetTextColor(0, 0, 0);
$pdf->SetFont('helvetica', '', 7);

$fill = false;
foreach ($trips as $trip) {
    $duration = $trip->actual_duration 
        ? floor($trip->actual_duration / 60) . 'h ' . ($trip->actual_duration % 60) . 'm'
        : floor($trip->planned_duration / 60) . 'h ' . ($trip->planned_duration % 60) . 'm';
    
    $rowData = [
        $trip->id,
        date('M j, Y H:i', strtotime($trip->start_datetime)),
        strlen($trip->destination) > 35 ? substr($trip->destination, 0, 35) . '...' : $trip->destination,
        $trip->requester_name,
        $trip->driver_name ?: '-',
        ucfirst($trip->status),
        $duration
    ];
    
    foreach ($rowData as $i => $val) {
        $pdf->Cell($colWidths[$i], 6, $val, 1, 0, 'L', $fill);
    }
    $pdf->Ln();
    $fill = !$fill;
}

$pdf->Ln(5);
$pdf->SetFont('helvetica', 'I', 8);
$pdf->Cell(0, 5, 'Total Trips: ' . count($trips) . ' | Generated by LOKA Fleet Management System on ' . date('Y-m-d H:i:s'), 0, 1, 'C');

$pdf->Output($filename . '.pdf', 'D');
exit;
