<?php
/**
 * LOKA - Export Driver Report to PDF
 */

requireRole(ROLE_APPROVER);

require_once BASE_PATH . '/vendor/tecnickcom/tcpdf/tcpdf.php';

$driverId = get('driver_id');
$startDate = get('start_date', date('Y-m-01'));
$endDate = get('end_date', date('Y-m-t'));

if (!$driverId) {
    redirectWith('/?page=reports&action=driver', 'danger', 'Please select a driver.');
}

$driverInfo = db()->fetch(
    "SELECT d.*, u.name, u.email, u.phone,
            dept.name as department_name
     FROM drivers d
     JOIN users u ON d.user_id = u.id
     LEFT JOIN departments dept ON u.department_id = dept.id
     WHERE d.id = ? AND d.deleted_at IS NULL",
    [$driverId]
);

if (!$driverInfo) {
    redirectWith('/?page=reports&action=driver', 'danger', 'Driver not found.');
}

$trips = db()->fetchAll(
    "SELECT r.id, r.start_datetime, r.end_datetime, r.purpose, r.destination,
            r.status, r.passenger_count, r.actual_dispatch_datetime, r.actual_arrival_datetime,
            u.name as requester_name, d.name as department_name,
            v.plate_number, v.make, v.model,
            TIMESTAMPDIFF(MINUTE, r.start_datetime, r.end_datetime) as planned_duration,
            TIMESTAMPDIFF(MINUTE, r.actual_dispatch_datetime, r.actual_arrival_datetime) as actual_duration
     FROM requests r
     JOIN users u ON r.user_id = u.id
     LEFT JOIN departments d ON r.department_id = d.id
     LEFT JOIN vehicles v ON r.vehicle_id = v.id
     WHERE r.driver_id = ? 
     AND r.start_datetime BETWEEN ? AND ?
     AND r.deleted_at IS NULL
     ORDER BY r.start_datetime DESC",
    [$driverId, $startDate, $endDate . ' 23:59:59']
);

$filename = 'driver_report_' . preg_replace('/[^a-zA-Z0-9]/', '_', $driverInfo->name) . '_' . $startDate . '_to_' . $endDate;
$title = 'Driver Report - ' . $driverInfo->name;

$pdf = new TCPDF('L', PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
$pdf->SetCreator('LOKA Fleet Management');
$pdf->SetAuthor(currentUser()->name);
$pdf->SetTitle($title);
$pdf->SetHeaderData('', 0, 'DICT - Driver Report', 
    $driverInfo->name . ' | Period: ' . $startDate . ' to ' . $endDate);
$pdf->setHeaderFont([PDF_FONT_NAME_MAIN, '', 10]);
$pdf->setFooterFont([PDF_FONT_NAME_DATA, '', 8]);
$pdf->SetMargins(10, 15, 10);
$pdf->SetAutoPageBreak(TRUE, 15);
$pdf->AddPage();
$pdf->SetFont('helvetica', '', 8);

$pdf->SetFont('helvetica', 'B', 10);
$pdf->Cell(0, 8, 'Driver Information', 0, 1);
$pdf->SetFont('helvetica', '', 9);
$pdf->Cell(40, 6, 'Name:', 0, 0);
$pdf->Cell(50, 6, $driverInfo->name, 0, 0);
$pdf->Cell(40, 6, 'Phone:', 0, 0);
$pdf->Cell(0, 6, $driverInfo->phone ?: '-', 0, 1);
$pdf->Cell(40, 6, 'License No:', 0, 0);
$pdf->Cell(50, 6, $driverInfo->license_number ?: '-', 0, 0);
$pdf->Cell(40, 6, 'License Expiry:', 0, 0);
$pdf->Cell(0, 6, $driverInfo->license_expiry ? date('M j, Y', strtotime($driverInfo->license_expiry)) : '-', 0, 1);
$pdf->Cell(40, 6, 'Department:', 0, 0);
$pdf->Cell(50, 6, $driverInfo->department_name ?: '-', 0, 0);
$pdf->Cell(40, 6, 'Status:', 0, 0);
$pdf->Cell(0, 6, ucfirst($driverInfo->status), 0, 1);
$pdf->Ln(5);

$columns = ['ID', 'Date/Time', 'Vehicle', 'Destination', 'Requester', 'Passengers', 'Status', 'Duration'];
$colWidths = [15, 40, 40, 55, 35, 18, 22, 25];

$pdf->SetFont('helvetica', 'B', 8);
$pdf->SetFillColor(13, 110, 253);
$pdf->SetTextColor(255, 255, 255);
foreach ($columns as $i => $col) {
    $pdf->Cell($colWidths[$i], 7, $col, 1, 0, 'C', true);
}
$pdf->Ln();

$pdf->SetFillColor(248, 248, 248);
$pdf->SetTextColor(0, 0, 0);
$pdf->SetFont('helvetica', '', 7);

$totalHours = 0;
$fill = false;
foreach ($trips as $trip) {
    $duration = $trip->actual_duration 
        ? floor($trip->actual_duration / 60) . 'h ' . ($trip->actual_duration % 60) . 'm'
        : floor($trip->planned_duration / 60) . 'h ' . ($trip->planned_duration % 60) . 'm';
    
    if ($trip->actual_duration) {
        $totalHours += $trip->actual_duration / 60;
    } elseif ($trip->planned_duration) {
        $totalHours += $trip->planned_duration / 60;
    }
    
    $vehicle = $trip->plate_number ? $trip->plate_number . ' - ' . $trip->make : '-';
    
    $rowData = [
        $trip->id,
        date('M j, Y H:i', strtotime($trip->start_datetime)),
        strlen($vehicle) > 25 ? substr($vehicle, 0, 25) . '...' : $vehicle,
        strlen($trip->destination) > 30 ? substr($trip->destination, 0, 30) . '...' : $trip->destination,
        $trip->requester_name,
        $trip->passenger_count,
        ucfirst($trip->status),
        $duration
    ];
    
    foreach ($rowData as $i => $val) {
        $pdf->Cell($colWidths[$i], 6, $val, 1, 0, 'L', $fill);
    }
    $pdf->Ln();
    $fill = !$fill;
}

$pdf->Ln(5);
$pdf->SetFont('helvetica', 'I', 8);
$pdf->Cell(0, 5, 'Total Trips: ' . count($trips) . ' | Total Hours: ' . number_format($totalHours, 1) . 'h | Generated by LOKA Fleet Management System on ' . date('Y-m-d H:i:s'), 0, 1, 'C');

$pdf->Output($filename . '.pdf', 'D');
exit;
